### ISSUE TITLE
Roadmap for Group Targeting

### ISSUE THREAD

**Issue by yellowjaguar5** [bitfocus/companion-module-liminalet-zoomosc#17]
- [ ] Multiple user selection (Primary: @ashgreen, let me know if you want me to work on any pieces)
    - [ ] Combine `singleuser` and `users` into **`user(s)`**
    - [ ] Allow multiple users to be supplied 
        - [ ] When multiple users are supplied, add `/users/` (e.g. `/zoom/users/galIndex/addPin 0 1` or `/zoom/allExcept/users/userName/mute "A" "B"`
        - [ ] Add quotes (`"`) escapement in regex for usernames that have quotes inside
        - [ ] Automatically divide on quotes for string or integer arguments
        - [ ] Also divide on spaces for integer arguments
- [ ] Selections group targeting (@yellowjaguar5 for now)
    - [ ] Handle group types: **`user(s)`, `all`, `tracked`, `allExcept`, and `trackedExcept`**
    - [ ] Look into adding panelist/attendee info to `list` output? 
        - [ ] If so, add `panelists`, `attendees`, `panelistsExcept`, and `attendeesExcept`

@ashgreen feel free to edit this as needed
